name: LLL

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
        with:
          path: project1
      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 26
      - name: Install dependencies
        run: npm ci  
      - name: Run app test
        run : npm test
