name: First Action

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print T1
        run: echo "Hello World !"
      - name: Print T1
        run: echo "Hello ok c'est non"
  second-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: J2
        run: |
            echo "T pipe"
            echo "T2 pipe"
